# Introdução ao NumPy - Base Computacional do Pandas

## Contexto Histórico e Importância

Criado em 2006, por Travis Oliphant, sua criação foi motivada devida a necessidade de computação científica eficiente em Python.

O Pandas é construído sobre o NumPy! Internamente, cada DataFrame e Series utiliza arrays NumPy para:

- Performance: Operações vetorizadas em C/Fortran

- Eficiência de memória: Arrays tipados vs listas Python

- Compatibilidade: Integração com ecossistema científico (SciPy, Matplotlib, Scikit-learn)

---

In [8]:
import numpy as np

## Bloco 1 - Diferença: Listas vs Arrays

**Comportamento de Listas Python**

In [9]:
lista_precos = [10, 20, 30]
print(f"Lista Python multiplicadas: {lista_precos * 2}")

Lista Python multiplicadas: [10, 20, 30, 10, 20, 30]


Características das listas Python:

- Multiplicação: Replica elementos (concatenação)

- Tipos mistos: Pode conter int, str, float simultaneamente

- Overhead: Cada elemento é um objeto Python completo

- Operações: Requerem loops explícitos para matemática

---

## Bloco 2 - Poder dos Arrays NumPy

**Operações Vetorizadas**

In [10]:
array_precos = np.array([10, 20, 30])
print(f"Lista Python multiplicadas: {array_precos * 2}")

Lista Python multiplicadas: [20 40 60]


Vantagens dos arrays NumPy:

- Operações elemento-wise: Aplicadas a todos os valores simultaneamente

- Tipos homogêneos: Todos elementos do mesmo tipo (int64, float64, etc.)

- Eficiência: Implementado em C, muito mais rápido

- Sintaxe intuitiva: Operações matemáticas naturais

---

## Bloco 3 - Arrays Multidimensionais

**Estruturas N-Dimensionais**

In [11]:
# Altura, largura e profundidade

dimensoes = np.array([
    [10, 20, 30],
    [20, 25, 40],
    [30, 35, 50]
])

Conceitos fundamentais:

- Matriz 2D: 3 linhas (caixas) × 3 colunas (dimensões)

- Indexação: [linha, coluna] para acesso específico

- Aplicações: Dados tabulares, imagens, matrizes matemáticas

💡 Analogia: Como uma planilha Excel, mas com superpoderes matemáticos!

---

## Bloco 4 - Propriedades dos Arrays

**Inspeção de Estruturas**

In [12]:
print(dimensoes.shape) # (3, 3) - 3 linhas, 3 colunas
print(dimensoes.size) # Melhor do que len, pois sabe o espaço antes de ser perguntado. Nesse caso 9 espaços.
print(dimensoes.dtype) # dtype('int64') - Tipo dos dados

(3, 3)
9
int64


Propriedades essenciais:

- `.shape`: Dimensões do array (tupla com tamanhos por eixo)

- `.size`: Número total de elementos

- `.dtype`: Tipo de dados (int32, float64, bool, etc.)

- `.ndim`: Número de dimensões (1D, 2D, 3D, etc.)

---

## Bloco 5 - Indexação e Slicing Avançado

**Seleção Precisa de Dado**

In [13]:
primeira_caixa = dimensoes[0, :] # Primeira linha completa
todas = dimensoes[:] # Todas as linhas
alturas = dimensoes[:, 0] # Primeira coluna (alturas)

print(f"Primeira caixa: {primeira_caixa}\n")    # [10 20 30]
print(f"Todas as caixas:\n{todas}\n")           # Array completo  
print(f"Todas as alturas: {alturas}")           # [10 20 30]

Primeira caixa: [10 20 30]

Todas as caixas:
[[10 20 30]
 [20 25 40]
 [30 35 50]]

Todas as alturas: [10 20 30]


Sintaxe de indexação:

- `[linha, coluna]`: Seleção específica

- `[:]`: Seleciona tudo naquela dimensão

- `[0, :]`: Linha 0, todas as colunas

- `[:, 0]`: Todas as linhas, coluna 0

💡 Conexão com Pandas: Mesma lógica usada em `.iloc[]` e `.loc[]`.

---

## Bloco 6 - Operações Estatísticas

**Análise Rápida de Dados**

In [14]:
alturas = dimensoes[:, 0]           # [10, 20, 30]
media_alturas = np.mean(alturas)    # 20.0
media_geral = np.mean(dimensoes)    # 28.333...

print(f"Média das alturas: {media_alturas}")
print(f"Média geral: {media_geral:.2f}")

Média das alturas: 20.0
Média geral: 28.89


**Funções estatísticas NumPy:**

In [ ]:
np.mean()    # Média aritmética
np.median()  # Mediana
np.std()     # Desvio padrão
np.min()     # Valor mínimo
np.max()     # Valor máximo
np.sum()     # Soma total

💡 Performance: Implementadas em C, muito mais rápidas que equivalentes Python.

---

## Bloco 7 - Benchmark de Performance

**Comparação: NumPy vs Python Nativo**

In [15]:
import time

In [21]:
# Configuração do teste
n_transacoes = 10_000_000

# Dados NumPy
dados_numpy = np.random.rand(n_transacoes)

# Dados Python (lista)
dados_python = [np.random.rand() for _ in range(n_transacoes)]

print(f"Testando com {n_transacoes:,} transações...")

Testando com 10,000,000 transações...


In [22]:
# Teste NumPy
inicio = time.time()
resultado_numpy = np.mean(dados_numpy)
tempo_numpy = time.time() - inicio

print(f"NumPy:  {tempo_numpy:.4f}s - Resultado: {resultado_numpy:.6f}")

NumPy:  0.0221s - Resultado: 0.499905


In [23]:
# Teste Python
inicio = time.time()
resultado_python = sum(dados_python) / len(dados_python)
tempo_python = time.time() - inicio

print(f"Python: {tempo_python:.4f}s - Resultado: {resultado_python:.6f}")

Python: 0.0559s - Resultado: 0.500095


In [24]:
# Comparação
speedup = tempo_python / tempo_numpy

print(f"NumPy é {speedup:.1f}x mais rápido!")

NumPy é 2.5x mais rápido!


Aplicações Práticas:

- DataFrames grandes: Milhões de linhas processadas rapidamente

- Operações matemáticas: Cálculos financeiros, estatísticos

- Machine Learning: Algoritmos baseados em álgebra linear

- Visualizações: Matplotlib também usa NumPy

💡 Conceito Central: NumPy não é apenas uma biblioteca - é a infraestrutura que torna Python viável para ciência de dados. Sem NumPy, Pandas seria impossível!